### ISSUE TITLE
Failed to run setup

### ISSUE THREAD

**Issue by SeanSun0322** [workerindex/gdir#1]
![image](https://user-images.githubusercontent.com/47513742/80269313-3c8f2880-86e1-11ea-801c-87cff40aee30.png)
I installed the latest node.js with npm and golang toolchain from the official website, created SAs with AutoRclone, and received error messages as follows. Please help. Operating on CentOS 7.

**Comment by rixtox** [comment]
You probably forgot to do `npm install`. It's recommended to use the guided setup tool instead of manual, if you are not familiar with Node.js development.

**Comment by SeanSun0322** [comment]
> You probably forgot to do `npm install`. It's recommended to use the guided setup tool instead of manual, if you are not familiar with Node.js development.

It was the message I received when running go ./tools/setup. Just now I tried to run npm install, but got another error.
![image](https://user-images.githubusercontent.com/47513742/80269558-60536e00-86e3-11ea-871e-fc8aedcb52aa.png)

**Comment by rixtox** [comment]
Did you run it while inside `gdir`? Giving your log it seems you were under `/home/` and ran something like `go run ./gdir/tools/setup`. That won't work. You have to be inside `gdir` and run `go run ./tools/setup`.

**Comment by rixtox** [comment]
And btw `/home/` folder probably is not a good place to store any project related code. You probebly want to save those under a path your user has read/write access of.

**Comment by SeanSun0322** [comment]
I did run it inside gdir, like this. Still got the error. I have already run chmod -R 777 gdir.
![image](https://user-images.githubusercontent.com/47513742/80269853-eec8ef00-86e5-11ea-84b2-6dcf343172d9.png)

**Comment by rixtox** [comment]
Are you working at the path at `/home/gdir` for the project? Please use some other path like `/home/<your_user>/gdir` instead so you have access.

**Comment by SeanSun0322** [comment]
> Are you working at the path at `/home/gdir` for the project? Please use some other path like `/home/<your_user>/gdir` instead so you have access.

I used the root user, and originally I was working in /root/gdir. After receiving this error, I moved it to home. Moving it back didn't make a difference.

**Comment by rixtox** [comment]
Try removing `gdir/node_modules` folder and try again.

**Comment by rixtox** [comment]
Maybe the first time you got access error corrupted the `node_modules` folder.

**Comment by SeanSun0322** [comment]
![image](https://user-images.githubusercontent.com/47513742/80270144-2fc20300-86e8-11ea-9d48-00c8c5e99f43.png)
Still got the error... Strange...

**Comment by rixtox** [comment]
Try to do it with a normal user then. Could be some permission settings on your path and root.

**Comment by SeanSun0322** [comment]
> Try to do it with a normal user then. Could be some permission settings on your path and root.

WOW, it worked! I never met an error like this before. Thank you for your help!
